# Generated by Django 5.2 on 2025-04-11 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0017_alter_member_sunflower_acreage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('districts', models.ManyToManyField(related_name='agents', to='cooperatives.district')),
                ('farmer_groups', models.ManyToManyField(related_name='agents', to='cooperatives.farmergroup')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['agent_id'], name='agents_agen_agent_i_f18e23_idx'), models.Index(fields=['first_name', 'last_name'], name='agents_agen_first_n_ce966f_idx'), models.Index(fields=['email'], name='agents_agen_email_c3a8fb_idx'), models.Index(fields=['date_joined'], name='agents_agen_date_jo_08c5be_idx')],
            },
        ),
    ]
