# Generated by Django 5.2 on 2025-04-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('cooperatives', '0017_alter_member_sunflower_acreage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_agent_i_f18e23_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_first_n_ce966f_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_email_c3a8fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agents_agen_date_jo_08c5be_idx',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='agent',
            name='farmers_profiled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='districts',
            field=models.ManyToManyField(blank=True, to='cooperatives.district'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='farmer_groups',
            field=models.ManyToManyField(blank=True, to='cooperatives.farmergroup'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
