# Generated by Django 5.2 on 2025-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
