# Generated by Django 5.2 on 2025-04-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ['-created_at'], 'verbose_name': 'Global Incentive', 'verbose_name_plural': 'Global Incentives'},
        ),
        migrations.RemoveField(
            model_name='incentive',
            name='agent',
        ),
    ]
