# Generated by Django 5.2 on 2025-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_is_credit_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
