# Generated by Django 5.2 on 2025-04-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_unit_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cooperative',
        ),
    ]
