# Generated by Django 5.2 on 2025-04-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.product'),
        ),
    ]
