# Generated by Django 5.2 on 2025-04-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_cooperative_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmergroup',
            name='is_VSLA',
            field=models.BooleanField(default=False, verbose_name='Is VSLA'),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.parish'),
        ),
        migrations.AddField(
            model_name='farmergroup',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_groups', to='cooperatives.product'),
        ),
    ]
