# Generated by Django 5.2 on 2025-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_farmergroup_is_vsla_farmergroup_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='beehives',
            field=models.IntegerField(blank=True, help_text='Number of beehives', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='has_mobile_money',
            field=models.BooleanField(default=False, help_text='Whether the member has mobile money'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, help_text='Identification document number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voters_card', "Voter's Card"), ('refugee_id', 'Refugee ID'), ('other', 'Other')], help_text='Type of identification document', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_refugee',
            field=models.BooleanField(default=False, help_text='Whether the member is a refugee'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the member has been verified'),
        ),
        migrations.AddField(
            model_name='member',
            name='land_acres',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total land size in acres', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products cultivated by the member', related_name='member_products', to='cooperatives.product'),
        ),
        migrations.AddField(
            model_name='member',
            name='shea_trees',
            field=models.IntegerField(blank=True, help_text='Number of shea trees', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('vice', 'Vice'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('committee', 'Committee'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
