# Generated by Django 5.2 on 2025-04-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_member_beehives_member_has_mobile_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text="GPS coordinates as a single string (e.g. '2.90091247,33.35992853')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude coordinate of the member's location", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude coordinate of the member's location", max_digits=9, null=True),
        ),
    ]
