# Generated by Django 5.2 on 2025-04-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0009_remove_member_name_member_email_member_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Member's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(max_length=255),
        ),
    ]
