# Generated by Django 5.2 on 2025-04-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0010_member_date_of_birth_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
