# Generated by Django 5.2 on 2025-04-11 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0011_alter_member_first_name_alter_member_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, help_text='Identification document number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('vice', 'Vice'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('committee', 'Committee'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['first_name', 'surname'], name='cooperative_first_n_8c56aa_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['created_at', 'cooperative'], name='cooperative_created_1e6bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['district', 'county', 'sub_county'], name='cooperative_distric_31848c_idx'),
        ),
    ]
