# Generated by Django 5.2 on 2025-04-11 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0012_alter_member_created_at_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='members',
        ),
        migrations.AlterField(
            model_name='member',
            name='farmer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_members', to='cooperatives.farmergroup'),
        ),
    ]
