# Generated by Django 5.2 on 2025-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0013_remove_cooperative_members_alter_member_farmer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Whether the member has been verified'),
        ),
    ]
