# Generated by Django 5.2 on 2025-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0014_alter_member_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the member has been verified'),
        ),
    ]
