# Generated by Django 5.2 on 2025-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0015_alter_member_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sunflower_acreage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='sunflower_planted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('chairperson', 'Chairperson'), ('vice', 'Vice'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('committee', 'Committee Member'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
    ]
