# Generated by Django 5.2 on 2025-04-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0016_member_sunflower_acreage_member_sunflower_planted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sunflower_acreage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total land available for sunflower cultivation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='sunflower_planted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual acreage planted with sunflowers', max_digits=10),
        ),
    ]
