# Generated by Django 5.2 on 2025-04-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0018_supplier_supplierprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products supplied by this supplier', related_name='suppliers', to='cooperatives.product'),
        ),
    ]
