# Generated by Django 5.2 on 2025-04-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0020_supplierproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products supplied by this supplier', related_name='supplier_products', to='cooperatives.product'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products_list', to='cooperatives.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
    ]
