# Generated by Django 5.2 on 2025-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0022_alter_supplier_address_alter_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('agro_inputs', 'Agro Inputs')], max_length=20, null=True),
        ),
    ]
