# Generated by Django 5.2 on 2025-04-12 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0023_supplierproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.unit'),
        ),
    ]
