# Generated by Django 5.2 on 2025-04-22 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0025_alter_supplier_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(help_text='put 0 if no contact is provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('agro_inputs', 'Agro Inputs'), ('phones', 'Phones'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(help_text='Date when the product was collected')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of product collected', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity * unit_price)', max_digits=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C'), ('D', 'Grade D')], default='A', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cooperatives.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cooperatives.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='cooperatives.unit')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'indexes': [models.Index(fields=['member', 'product'], name='cooperative_member__81b1c7_idx'), models.Index(fields=['collection_date'], name='cooperative_collect_877fab_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlantingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_acres', models.DecimalField(decimal_places=2, help_text='Number of acres allocated for this product', max_digits=10)),
                ('planting_date', models.DateField(blank=True, help_text='Date when planting was done', null=True)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='Expected date of harvest', null=True)),
                ('actual_harvest_date', models.DateField(blank=True, help_text='Actual date of harvest', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_allocations', to='cooperatives.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_allocations', to='cooperatives.product')),
            ],
            options={
                'verbose_name': 'Planting Allocation',
                'verbose_name_plural': 'Planting Allocations',
                'indexes': [models.Index(fields=['member', 'product'], name='cooperative_member__0a12af_idx'), models.Index(fields=['planting_date', 'expected_harvest_date'], name='cooperative_plantin_1c4ddd_idx')],
                'unique_together': {('member', 'product', 'planting_date')},
            },
        ),
    ]
