# Generated by Django 5.2 on 2025-04-30 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0026_alter_supplier_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='planting_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='cooperatives.plantingallocation'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['planting_allocation'], name='cooperative_plantin_e5e9d0_idx'),
        ),
    ]
