# Generated by Django 5.2 on 2025-05-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0027_collection_planting_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingallocation',
            name='planting_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Number of seeds/seedlings planted or number of bee hives', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plantingallocation',
            name='planting_quantity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planting_allocations', to='cooperatives.unit'),
        ),
        migrations.AddField(
            model_name='plantingallocation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planting_allocations', to='cooperatives.supplier'),
        ),
    ]
