# Generated by Django 5.2 on 2025-05-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0028_plantingallocation_planting_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantingallocation',
            unique_together=set(),
        ),
    ]
