# Generated by Django 5.2 on 2025-05-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0030_creditmanager_loansupplier_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='system_id',
            field=models.CharField(blank=True, help_text='External system ID for the member', max_length=50, null=True, unique=True),
        ),
    ]
