# Generated by Django 5.2 on 2025-05-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0032_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_reference',
            field=models.CharField(blank=True, help_text='Unique reference for the collection', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='collection_reference',
            field=models.CharField(blank=True, help_text='Unique reference for the collection', max_length=255, null=True, unique=True),
        ),
    ]
